site_name: Test API
site_description: Documentation for the Test API project
site_url: https://tylerpitcher.github.io/test/

theme:
  name: material
  features:
    # - navigation.tabs
    - navigation.expand
    - navigation.sections
    - content.code.copy
    - search.highlight

nav:
  - Home: index.md
  - Guides:
      - Getting Started: getting-started.md
      - Deployment: deployment.md
  - Architecture:
      - Overview: architecture.md
  - API:
      - API Reference: api-reference.md
